---
title: "other part"
author: "Xinyi Lin"
date: "12/5/2018"
output: html_document
---


```{r}
library(tidyverse)
```

# Import and tidy data

First, we should have a roughly understanding about this data.

```{r}
#mentalhealth_2014_df = read_csv("./data/mental_health_in_tech_2014.csv") 
mentalhealth_2016_df = read_csv("./data/mental_health_in_tech_2016.csv") 
```

```{r}
colnames(mentalhealth_2016_df) <- c("self_employed", "num_employees", "tech_company", "tech_role", "benefits", "care_options", "employer_discussion", "employer_help", "anonymity", "medical_leave", "mental_health_consequences", "physical_health_consequences", "coworkers_discussion", "supervisor_discussion", "mental_vs_physical", "obs_consequence", "medical_coverage", "help_resourcces", "whether_reveal_business_contacts", "reveal_concequences_business_contects", "whether_reveal_coworkers", "reveal_concequences_coworkers", "productivity_affect", "work_time_affected", "preemployers", "preemployers_benefits", "preemployers_care_options", "preemployers_discussion", "preemployer_help", "pre_anonymity", "pre_mental_health_consequences", "pre_physical_health_consequences", "pre_coworkers_discussion", "pre_supervisors_discussion", "pre_mental_vs_physical", "pre_obs_consequence", "physical_health_interview", "physical_health_interview_reason", "mental_health_interview", "mental_health_interview_reason", "career_influence", "coworkers_view", "friends_family_share", "unsupportive_badly_handled", "less_likely_reveal", "family_history", "mental_health_previous", "mental_health_now", "condition_diagnosed", "possible_condition", "professional_diagnosed", "condition_professional_diagnosed", "seek_treatment", "work_interferes_treated", "work_interferes_untreated", "age", "gender", "country_live", "territory_live", "country_work", "territory_work", "work_position_kind", "work_remotely")
```

```{r}
summary(as.factor(mentalhealth_2016_df$gender))
summary(as.factor(mentalhealth_2016_df$country_work))
summary(mentalhealth_2016_df$age)

mentalhealth_2016_df %>% 
  ggplot(aes(x = age)) +
  geom_density()
```

```{r}
mentalhealth_2016_tidied =
  mentalhealth_2016_df %>% 
  filter(age < 100) %>% 
  mutate(gender = str_replace(gender, "^[Ww]oman$", "Female"),     # female
         gender = str_replace(gender, "^[Ff]$", "Female"),
         gender = str_replace(gender, "^fem$", "Female"),
         gender = str_replace(gender, "^female$", "Female"),
         gender = str_replace(gender, "^female/woman$", "Female"),
         gender = str_replace(gender, "^fm$", "Female"),
         gender = str_replace(gender, "AFAB", "Female"),
         #gender = str_replace(gender, "AFAB", "Female"),
         gender = str_replace(gender, "^[Mm]$", "Male"),  # male
         gender = str_replace(gender, "^mail$", "Male"),  #?
         gender = str_replace(gender, "^MALE$", "Male"),
         gender = str_replace(gender, "^Male.$", "Male"),
         gender = str_replace(gender, "^Malr$", "Male"),    #?
         gender = str_replace(gender, "^[Mm]an$", "Male"),
         #gender = str_replace(gender, "^man$", "Male"),
         gender = str_replace(gender, "^male$", "Male"))

#summary(as.factor(mentalhealth_2016_df$gender))
#summary(mentalhealth_2016_df$age)   # need filter 99 or not?

head(mentalhealth_2016_df)
```

# mental_vs_physical

```{r}
mental_vs_physical =
  mentalhealth_2016_df %>% 
  #filter(tech_company != 0 | tech_role != 0) 
  #select(num_employees, tech_company, tech_role, benefits, )
  select(contains("mental"), contains("physical")) %>% 
  select(-contains("previous"))
```

```{r}
mentalhealth_2016_tidied %>% 
  group_by(num_employees, mental_health_now) %>% 
  summarise(n = n()) %>% 
  spread(key = mental_health_now, value = n) %>% 
  mutate(total = Maybe + No + Yes,
         mentalhealth_now_precentage = Yes/total) 
```

```{r}
mentalhealth_2016_tidied %>% 
  filter(mental_health_now == "Yes" | mental_health_now == "No") %>% 
  ggplot(aes(x = num_employees)) +
  geom_bar(aes(fill = mental_health_now))
  
mentalhealth_2016_tidied
```





# add id and split disorder

```{r}
# add_id
mentalhealth_2016_tidied$ID = seq.int(nrow(mentalhealth_2016_tidied))

# split Mental health disorders(for example, one person has several kinds of MH disorders)
df = 
  mentalhealth_2016_tidied %>% 
  select(country_work, territory_work, mental_health_now, condition_diagnosed) %>% 
  mutate(condition_diagnosed = str_split(condition_diagnosed, "\\|")) %>% 
  unnest(condition_diagnosed) 
```

```{r}
other_condition_df =
  df %>% 
  group_by(condition_diagnosed) %>% 
  summarise(n = n()) %>% arrange(desc(n)) %>% 
  filter(n == 1)

other_condition_l = other_condition_df$condition_diagnosed

shinymap_df =
  df %>% 
  mutate(condition_diagnosed = ifelse(condition_diagnosed %in% other_condition_l, "other", condition_diagnosed))
```