---
title: "sc4456"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(tidytext)
```

```{r}
mentalhealth_2016_df = read_csv("./data/mental_health_in_tech_2016.csv") 
colnames(mentalhealth_2016_df) <- c("self_employed", "num_employees", "tech_company", "tech_role", "benefits", "care_options", "employer_discussion", "employer_help", "anonymity", "medical_leave", "mental_health_consequences", "physical_health_consequences", "coworkers_discussion", "supervisor_discussion", "mental_vs_physical", "obs_consequence", "medical_coverage", "help_resourcces", "whether_reveal_business_contacts", "reveal_concequences_business_contects", "whether_reveal_coworkers", "reveal_concequences_coworkers", "productivity_affect", "work_time_affected", "preemployers", "preemployers_benefits", "preemployers_care_options", "preemployers_discussion", "preemployer_help", "pre_anonymity", "pre_mental_health_consequences", "pre_physical_health_consequences", "pre_coworkers_discussion", "pre_supervisors_discussion", "pre_mental_vs_physical", "pre_obs_consequence", "physical_health_interview", "physical_health_interview_reason", "mental_health_interview", "mental_health_interview_reason", "career_influence", "coworkers_view", "friends_family_share", "unsupportive_badly_handled", "less_likely_reveal", "family_history", "mental_health_previous", "mental_health_now", "condition_diagnosed", "possible_condition", "professional_diagnosed", "condition_professional_diagnosed", "seek_treatment", "work_interferes_treated", "work_interferes_untreated", "age", "gender", "country_live", "territory_live", "country_work", "territory_work", "work_position_kind", "work_remotely")
attach(mentalhealth_2016_df)
```
#### table for medical leave difficulty

```{r}

#### table for medical leave difficulty
summary(as.factor(medical_leave)) %>% knitr::kable() 

```


### mental_health_interview_reason for employee in tech company

```{r}
### mental_health_interview_reason

MH_interview_reason_inspec = mentalhealth_2016_df %>% filter(tech_company == 1) 
MH_interview_reason_inspec= MH_interview_reason_inspec %>% unnest_tokens(word, mental_health_interview_reason)

data(stop_words)
MH_interview_reason_inspec  = 
  anti_join(MH_interview_reason_inspec, stop_words) 

MH_interview_reason_inspec  %>% count(word, sort = TRUE) %>% 
  top_n(20) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) +
  geom_bar(stat = "identity", fill = "blue", alpha = 0.6) +
  coord_flip()
```

### Condition_diagonised

```{r}

```



