---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rvest)
library(ggmap)
library(maps)
library(plotly)
library(scatterpie)
library(leaflet)
library(shiny)
```

```{r}
# Import and tidy data

mentalhealth_2016_df = read_csv("./data/mental_health_in_tech_2016.csv") 
colnames(mentalhealth_2016_df) <- c("self_employed", "num_employees", "tech_company", "tech_role", "benefits", "care_options", "employer_discussion", "employer_help", "enonymity", "medical_leave", "mental_health_consequences", "phys_health_consequences", "coworkers_discussion", "supervisor_discussion", "mental_vs_physical", "obs_consequence", "medical_coverage", "help_resourcces", "whether_reveal_business_contacts", "reveal_concequences_business_contects", "whether_reveal_coworkers", "reveal_concequences_coworkers", "productivity_affect", "work_time_affected", "preemployers", "preemployers_benefits", "preemployers_care_options", "preemployers_discussion", "preemployer_help", "pre_anonymity", "pre_mental_health_consequences", "pre_phys_health_consequences", "pre_coworkers_discussion", "pre_supervisors_discussion", "pre_mental_vs_physical", "pre_obs_consequence", "physical_health_interview", "physical_health_interview_reason", "mental_health_interview", "mental_health_interview_reason", "career_influence", "coworkers_view", "friends_family_share", "unsupportive_badly_handled", "less_likely_reveal", "family_history", "mental_health_previous", "mental_health_now", "condition_diagnosed", "possible_condition", "professional_diagnosed", "condition_professional_diagnosed", "seek_treatment", "work_interferes_treated", "work_interferes_untreated", "age", "gender", "country_live", "territory_live", "country_work", "territory_work", "work_position_kind", "work_remotely")
```

```{r}
mentalhealth_2016_tidied =
  mentalhealth_2016_df %>% 
  filter(age < 100) %>% 
  mutate(gender = str_replace(gender, "^[Ww]oman$", "Female"),     # female
         gender = str_replace(gender, "^[Ff]$", "Female"),
         gender = str_replace(gender, "^fem$", "Female"),
         gender = str_replace(gender, "^female$", "Female"),
         gender = str_replace(gender, "^female/woman$", "Female"),
         gender = str_replace(gender, "^fm$", "Female"),
         gender = str_replace(gender, "AFAB", "Female"),
         #gender = str_replace(gender, "AFAB", "Female"),
         gender = str_replace(gender, "^[Mm]$", "Male"),  # male
         gender = str_replace(gender, "^mail$", "Male"),  #?
         gender = str_replace(gender, "^MALE$", "Male"),
         gender = str_replace(gender, "^Male.$", "Male"),
         gender = str_replace(gender, "^Malr$", "Male"),    #?
         gender = str_replace(gender, "^[Mm]an$", "Male"),
         #gender = str_replace(gender, "^man$", "Male"),
         gender = str_replace(gender, "^male$", "Male"))
```

```{r}
# add id and split disorder

# add_id
mentalhealth_2016_tidied$ID = seq.int(nrow(mentalhealth_2016_tidied))

# split Mental health disorders(for example, one person has several kinds of MH disorders)
df = 
  mentalhealth_2016_tidied %>% 
  select(country_work, territory_work, mental_health_now, condition_diagnosed) %>% 
  mutate(condition_diagnosed = str_split(condition_diagnosed, "\\|")) %>% 
  unnest(condition_diagnosed) 
```

```{r}
# tidy disorder

other_condition_df =
  df %>% 
  group_by(condition_diagnosed) %>% 
  summarise(n = n()) %>% arrange(desc(n)) %>% 
  filter(n == 1)

other_condition_l = other_condition_df$condition_diagnosed

shinymap_df =
  df %>% 
  mutate(condition_diagnosed = ifelse(condition_diagnosed %in% other_condition_l, "other", condition_diagnosed))
```

```{r}
# add other data and combind them together

state_geo = read_csv("./data/statelatlong.csv") %>% 
  janitor::clean_names()

capital_coord = read_csv("./data/country-capitals.csv") %>% 
  janitor::clean_names() %>% 
  select(country_name, capital_name, capital_longitude, capital_latitude)

map_US = shinymap_df %>% 
  filter(country_work == "United States of America") 

map_US = merge(map_US, state_geo, by.x = "territory_work", by.y = "city") %>% 
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude))

map_other = shinymap_df %>% 
  filter(country_work != "United States of America") 

map_other = merge(map_other, capital_coord, by.x = "country_work", by.y = "country_name") %>% 
  select(-territory_work) 

colnames(map_other) = c("country_work","mental_health_now","condition_diagnosed","territory_work", "longitude", "latitude" )

map_other = map_other %>% 
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude))

map_all = full_join(map_other,map_US)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# get choice
condition = map_all %>% distinct(condition_diagnosed) %>% pull()
answer = map_all %>% distinct(mental_health_now) %>% pull()
#answer = c("Yes", "No", "Maybe")

# selectInput widget
selectInput("condition_choice", label = h3("Select condition"),
            choices = condition, selected = "Anxiety Disorder (Generalized, Social, Phobia, etc)")

# radioButtons widget
radioButtons("answer_choice", label = h3("Choose answer"),
    choices = answer, selected = "No")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
LeafletInput = reactive({
  map_all %>%
    #filter(condition_diagnosed == input$condition_choice, mental_health_now == input$answer_choice)
    filter(mental_health_now == input$answer_choice, condition_diagnosed == input$condition_choice)
})

renderLeaflet({
 LeafletInput() %>% 
    #leaflet(data = map_all) %>%
    leaflet() %>% 
    addTiles() %>%
    addMarkers(lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions())})


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```







