---
title: "tree_model"
author: "Xinyi Lin"
date: "12/5/2018"
output: html_document
---

```{r}
library(tidyverse)
```

# Import and tidy data

First, we should have a roughly understanding about this data.

```{r}
#mentalhealth_2014_df = read_csv("./data/mental_health_in_tech_2014.csv") 
mentalhealth_2016_df = read_csv("./data/mental_health_in_tech_2016.csv") 
```

```{r}
colnames(mentalhealth_2016_df) <- c("self_employed", "num_employees", "tech_company", "tech_role", "benefits", "care_options", "employer_discussion", "employer_help", "anonymity", "medical_leave", "mental_health_consequences", "physical_health_consequences", "coworkers_discussion", "supervisor_discussion", "mental_vs_physical", "obs_consequence", "medical_coverage", "help_resourcces", "whether_reveal_business_contacts", "reveal_concequences_business_contects", "whether_reveal_coworkers", "reveal_concequences_coworkers", "productivity_affect", "work_time_affected", "preemployers", "preemployers_benefits", "preemployers_care_options", "preemployers_discussion", "preemployer_help", "pre_anonymity", "pre_mental_health_consequences", "pre_physical_health_consequences", "pre_coworkers_discussion", "pre_supervisors_discussion", "pre_mental_vs_physical", "pre_obs_consequence", "physical_health_interview", "physical_health_interview_reason", "mental_health_interview", "mental_health_interview_reason", "career_influence", "coworkers_view", "friends_family_share", "unsupportive_badly_handled", "less_likely_reveal", "family_history", "mental_health_previous", "mental_health_now", "condition_diagnosed", "possible_condition", "professional_diagnosed", "condition_professional_diagnosed", "seek_treatment", "work_interferes_treated", "work_interferes_untreated", "age", "gender", "country_live", "territory_live", "country_work", "territory_work", "work_position_kind", "work_remotely")
```

```{r}
mentalhealth_2016_tidied =
  mentalhealth_2016_df %>% 
  filter(age < 100) %>% 
  mutate(gender = str_replace(gender, "^[Ww]oman$", "Female"),     # female
         gender = str_replace(gender, "^[Ff]$", "Female"),
         gender = str_replace(gender, "^fem$", "Female"),
         gender = str_replace(gender, "^female$", "Female"),
         gender = str_replace(gender, "^female/woman$", "Female"),
         gender = str_replace(gender, "^fm$", "Female"),
         gender = str_replace(gender, "AFAB", "Female"),
         #gender = str_replace(gender, "AFAB", "Female"),
         gender = str_replace(gender, "^[Mm]$", "Male"),  # male
         gender = str_replace(gender, "^mail$", "Male"),  #?
         gender = str_replace(gender, "^MALE$", "Male"),
         gender = str_replace(gender, "^Male.$", "Male"),
         gender = str_replace(gender, "^Malr$", "Male"),    #?
         gender = str_replace(gender, "^[Mm]an$", "Male"),
         #gender = str_replace(gender, "^man$", "Male"),
         gender = str_replace(gender, "^male$", "Male"))

head(mentalhealth_2016_df)
```

# model building

```{r}
mental_data_fit = 
  mentalhealth_2016_tidied %>%
  mutate(tech = ifelse(tech_company == 1 | tech_role == 1, 1, 0)) %>%
  filter(mental_health_now != "Maybe") %>% 
  filter(gender == "Male" | gender == "Female") %>% 
  filter(!is.na(num_employees) & !is.na(tech) & !is.na(family_history) & !is.na(mental_health_previous) & !is.na(age) & !is.na(gender) & !is.na(work_remotely) & !is.na(mental_health_now)) %>%
  mutate(num_employees = as.factor(num_employees), 
         tech_company = as.factor(tech_company), 
         tech_role = as.factor(tech_role), 
         family_history = as.factor(family_history), 
         mental_health_previous = as.factor(mental_health_previous), 
         gender = as.factor(gender), 
         work_remotely = as.factor(work_remotely), 
         mental_health_now = as.factor(mental_health_now)) %>%
  #select(mental_health_now, num_employees, tech, family_history, mental_health_previous, age, gender, work_remotely)
  select(mental_health_now, num_employees, tech, family_history, age, gender, work_remotely)
```

## using random forest

```{r}
library(randomForest)
index <- sample(2,nrow(mental_data_fit),replace = TRUE,prob = c(0.7,0.3))
traindata <- mental_data_fit[index == 1,]
testdata <- mental_data_fit[index == 2,]
```

decide ntree

```{r}
set.seed(13)
rf_ntree <- randomForest(mental_health_now ~.,data=traindata,ntree=300)
plot(rf_ntree)
```

```{r}
mentalhealth_rf <- randomForest(mental_health_now ~ ., data = traindata, ntree = 300, proximity = TRUE)

mentalhealth_rf

importance(mentalhealth_rf)
```

show random forest

```{r}
MDSplot(mentalhealth_rf, mental_data_fit$mental_health_now)
```

test model

```{r}
mentalhealth_pred <- predict(mentalhealth_rf,newdata = testdata)
table(mentalhealth_pred,testdata$mental_health_now)

plot(margin(mentalhealth_rf, testdata$mental_health_now))
```

## using conditional inference tree

```{r}
library(party)

set.seed(3)

index <- sample(2,nrow(mental_data_fit),replace = TRUE,prob = c(0.7,0.3))
traindata <- mental_data_fit[index == 1,]
testdata <- mental_data_fit[index == 2,]
```

```{r}
fitted_ctree <- ctree(mental_health_now ~ ., data = traindata)
plot(fitted_ctree, main = "Conditional Inference Tree")
```

```{r}
ctree.pred <- predict(fitted_ctree, testdata, type = "response")
ctree.perf <- table(testdata$mental_health_now, ctree.pred, 
                    dnn = c("Actual", "Predicted"))

library(caret)
confusionMatrix(table(ctree.pred,testdata$mental_health_now))
```

## decision tree

```{r}
library(rpart)
library(rpart.plot)

set.seed(13)
 
index <- sample(2,nrow(mental_data_fit),replace = TRUE,prob = c(0.7,0.3))
traindata <- mental_data_fit[index == 1,]
testdata <- mental_data_fit[index == 2,]
```

```{r}
fitted_dtree <- rpart(formula = mental_health_now ~ ., data = traindata, method = 'class')

rpart.plot(fitted_dtree)
```

```{r}
dtree_pred <- predict(object = fitted_dtree,newdata = testdata,type = 'class')
table(dtree_pred, testdata$mental_health_now)
confusionMatrix(table(dtree_pred,testdata$mental_health_now))
```

